[package]
name = "cubecl-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cubecl = { version = "0.5.0", features = ["wgpu"] }
image = "0.25.6"

[[example]]
name = "blur_image"
path = "examples/blur_image/main.rs"

[[example]]
name = "flip_image"
path = "examples/flip_image/main.rs"
